# Generated by Django 3.1.3 on 2020-11-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_end',
            new_name='session_end_year',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_start',
            new_name='session_start_year',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
